#!/bin/bash
#I really wish this could be my own platform to write to people, but how many people are going to read it :(
#I'll still write anyways
#Okay so I'm presently doing ALX Internship and it has been cool so far even though it's time consuming
#I'll still do it anyways and complete it.
#I has made me time consious (OMG I can't spell consious again, It doesn't look right but I'll leave it anyways)
#My space
#Commands I have learnt during this internship during the second month learning Bash Script
grep, cd, cd~, mkdir, vim, echo, wc, git add, *, $(()), man, cp, mv, rm, 
